spring:
  datasource:
    driver-class-name: org.h2.Driver
    password:
    username: sa
    url: jdbc:h2:mem:testdb
  jpa:
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: true
      path: /h2-console
  application:
    name: spring-object-mapper
